"""Initial schema based on current models including salt and nonce

Revision ID: 0d23c3be02cb
Revises: 
Create Date: 2025-05-21 18:24:42.385219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d23c3be02cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encryption_salt', sa.LargeBinary(length=16), nullable=True))
        batch_op.add_column(sa.Column('encryption_nonce', sa.LargeBinary(length=12), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('encryption_nonce')
        batch_op.drop_column('encryption_salt')

    # ### end Alembic commands ###
